name: capstone_edu_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter_markdown: ^0.6.18 #8/12병합

  flutter_dotenv: ^5.1.0 #8/12병합
  flutter:
    sdk: flutter
  intl: ^0.19.0 #민경은 0.19.0 수민 코드는 0.20.2
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.9
  path_drawing: ^1.0.1
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2  # ✅ 이것만 남기고 나머지 shared_preferences 제거
  provider: ^6.1.1
  flutter_secure_storage: 8.1.0
  google_fonts: ^6.1.0
  flutter_colorpicker: ^1.1.0
  file_selector: ^1.0.1
  cached_network_image: ^3.3.1
  phosphor_flutter: ^2.1.0
  fl_chart: ^0.66.0  # (>=0.55.0 이상이면 AxisTitles/SideTitles 지원)
  share_plus: ^7.2.1
  path_provider: ^2.1.4
  pdf: ^3.10.8     # 최신 근처 버전 사용
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/logo_without_letter.png
    - assets/note_placeholder.png
    - assets/.env