"""add row_plan_id to plan table

Revision ID: 516497063732
Revises: 65b35354d5c9
Create Date: 2025-08-06 17:24:58.775353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516497063732'
down_revision: Union[str, None] = '65b35354d5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('row_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan', 'row_plan', ['row_plan_id'], ['row_plan_id'], ondelete='SET NULL')
    op.create_unique_constraint('uc_user_study_date', 'user_study_daily', ['user_id', 'study_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_user_study_date', 'user_study_daily', type_='unique')
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'row_plan_id')
    # ### end Alembic commands ###
