"""Add missing_days to user_type_history

Revision ID: 60f4625f3646
Revises: b8f1ac135158
Create Date: 2025-08-08 10:06:40.325599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f4625f3646'
down_revision: Union[str, None] = 'b8f1ac135158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'row_plan', 'plan', ['plan_id'], ['plan_id'])
    op.add_column('user_type_history', sa.Column('missing_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_type_history', 'missing_days')
    op.drop_constraint(None, 'row_plan', type_='foreignkey')
    # ### end Alembic commands ###
