"""add user_study_daily table

Revision ID: 65b35354d5c9
Revises: b7d45fcde915
Create Date: 2025-08-03 07:03:08.468949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b35354d5c9'
down_revision: Union[str, None] = 'b7d45fcde915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_study_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('morning_minutes', sa.Integer(), nullable=True),
    sa.Column('afternoon_minutes', sa.Integer(), nullable=True),
    sa.Column('evening_minutes', sa.Integer(), nullable=True),
    sa.Column('night_minutes', sa.Integer(), nullable=True),
    sa.Column('repetition', sa.Integer(), nullable=True),
    sa.Column('daily_achievement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_study_daily_id'), 'user_study_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_study_daily_id'), table_name='user_study_daily')
    op.drop_table('user_study_daily')
    # ### end Alembic commands ###
