"""fix: add user_type_history with varchar length

Revision ID: b7d45fcde915
Revises: d6c72d2f711d
Create Date: 2025-07-31 19:28:14.443244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d45fcde915'
down_revision: Union[str, None] = 'd6c72d2f711d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('sincerity', sa.String(length=20), nullable=False),
    sa.Column('repetition', sa.String(length=20), nullable=False),
    sa.Column('timeslot', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_type_history_id'), 'user_type_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_type_history_id'), table_name='user_type_history')
    op.drop_table('user_type_history')
    # ### end Alembic commands ###
