"""Add plan_id to row_plan

Revision ID: b8f1ac135158
Revises: 516497063732
Create Date: 2025-08-06 18:23:23.158977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8f1ac135158'
down_revision: Union[str, None] = '516497063732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plan_ibfk_3', 'plan', type_='foreignkey')
    op.drop_column('plan', 'row_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('row_plan_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plan_ibfk_3', 'plan', 'row_plan', ['row_plan_id'], ['row_plan_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
